# -*- coding: utf-8 -*-
"""session-22 descriptive statistics and visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZozAD6a6iCgqATV2fgQl1t75fvKuyHHW

#session-22 visulation below and the stats are in the copy

#visualisation
"""

# create 3 list here
price = [40000 , 54000 , 57000 , 49000 , 45000]
profit = [45000 , 6500 , 23000 , 45000 , 40000]
year = [2015 , 2016 , 2017 , 2018 , 2019 ]

"""#line plot or line chart"""

# now we will see the 2d line plot which can be used for bivariate analysis
 # 2d line plot -- for bivariate analysis
# mainly used for cat - num and num - num colm
# mainly used for timeseries analysis

# import library
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# sunce in will be bivariate analysis so we will have 2 colms
#
# plot the year and price in the x and y  axis respectively
plt.plot(year , price , label = 'price')


# now we willl analse the profit
plt.plot(year , profit , label = 'profit')

# now we will print the legend
plt.legend(loc = 'best')

# we will give a title
plt.title('year vs price and profit')

# now for the label in the x and the y axis
plt.xlabel("price")
plt.ylabel("amount")

# we want to change the color
# sunce in will be bivariate analysis so we will have 2 colms
#
# plot the year and price in the x and y  axis respectively
plt.plot(year , price , label = 'price' , color  = "blue")


# now we willl analse the profit
plt.plot(year , profit , label = 'profit' , color = 'yellow')

# now we will print the legend
plt.legend(loc = 'best')

# we will give a title
plt.title('year vs price and profit')

# now for the label in the x and the y axis
plt.xlabel("price")
plt.ylabel("amount")

# the lines plotted are very thin how to make them thick
# sunce in will be bivariate analysis so we will have 2 colms
#
# plot the year and price in the x and y  axis respectively
plt.plot(year , price , label = 'price' , linewidth  = 5)


# now we willl analse the profit
plt.plot(year , profit , label = 'profit' , linewidth = 7)

# now we will print the legend
plt.legend(loc = 'best')

# we will give a title
plt.title('year vs price and profit')

# now for the label in the x and the y axis
plt.xlabel("price")
plt.ylabel("amount")

# to cchnage the style of the line
# the lines plotted are very thin how to make them thick
# sunce in will be bivariate analysis so we will have 2 colms
#
# plot the year and price in the x and y  axis respectively
plt.plot(year , price , label = 'price' , linewidth  = 3 ,linestyle = 'dotted')


# now we willl analse the profit
plt.plot(year , profit , label = 'profit' , linewidth = 2 , linestyle = 'dashed')

# now we will print the legend
plt.legend(loc = 'best')

# we will give a title
plt.title('year vs price and profit')

# now for the label in the x and the y axis
plt.xlabel("price")
plt.ylabel("amount")

# now if we want to mark the data points in the graph so we will use marker
# to cchnage the style of the line
# the lines plotted are very thin how to make them thick
# sunce in will be bivariate analysis so we will have 2 colms
#
# plot the year and price in the x and y  axis respectively
plt.plot(year , price , label = 'price' , linewidth  = 3 ,linestyle = 'dotted' , marker = 'D')


# now we willl analse the profit
plt.plot(year , profit , label = 'profit' , linewidth = 2 , linestyle = 'dashed' , marker = 's')

# now we will print the legend
plt.legend(loc = 'best')

# we will give a title
plt.title('year vs price and profit')

# now for the label in the x and the y axis
plt.xlabel("price")
plt.ylabel("amount")

# to change the marker size
 # now if we want to mark the data points in the graph so we will use marker
# to cchnage the style of the line
# the lines plotted are very thin how to make them thick
# sunce in will be bivariate analysis so we will have 2 colms
#
# plot the year and price in the x and y  axis respectively
plt.plot(year , price , label = 'price' , linewidth  = 3 ,linestyle = 'dotted' , marker = 'D' , markersize = 5)


# now we willl analse the profit
plt.plot(year , profit , label = 'profit' , linewidth = 2 , linestyle = 'dashed' , marker = 's' , markersize = 4)

# now we will print the legend
plt.legend(loc = 'best')

# we will give a title
plt.title('year vs price and profit')

# now for the label in the x and the y axis
plt.xlabel("price")
plt.ylabel("amount")

